/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登录 */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新会话 */
        post: operations["authRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退出登录 */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 激活当前设备 */
        post: operations["clientActivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上报设备心跳 */
        post: operations["clientHeartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取客户端当前用户、设备和权限摘要 */
        get: operations["clientProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/model-leases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 申请模型租约 */
        post: operations["createModelLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/model-leases/{lease_id}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 续租模型租约 */
        post: operations["renewModelLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/model-leases/{lease_id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 释放模型租约 */
        post: operations["releaseModelLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client/llm/call-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 记录 Rust 直连模型调用摘要
         * @description Rust 使用当前 `direct_lease` 直接调用租约指定的 OpenAI-compatible 供应商；Go 不接收话术正文、视频或完整音频文件。
         *     本接口只记录 client_call_id、lease_id、provider/model、usage、延迟、状态和错误摘要；Go 生成服务端 request_id，客户端上报的 usage 必须标记为 `client_reported`。
         */
        post: operations["recordDirectLLMCall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改本地管理员密码
         * @description 仅本地管理员可调用；成功后撤销该管理员的所有会话，响应不返回密码。
         */
        post: operations["changeLocalAdminPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询用户列表 */
        get: operations["listAdminUsers"];
        put?: never;
        /**
         * 创建用户
         * @description 仅内建本地管理员可调用；创建全局用户身份。
         */
        post: operations["createAdminUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询用户设备 */
        get: operations["listAdminUserDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/authorization-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询用户授权与软额度摘要
         * @description 仅内建本地管理员可调用；返回设备、活动租约、活动模型账号和客户端自报日用量；当前没有供应商权威用户额度。
         */
        get: operations["getAdminUserAuthorizationSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/authorization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 更新用户模型授权与服务端记录用量门禁
         * @description 仅内建本地管理员可调用；空模型列表表示允许所有已登记模型；daily_token_limit 只约束服务端已接收的客户端用量记录，不是供应商权威计费或未来用量预占。
         */
        patch: operations["updateAdminUserAuthorization"];
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 禁用用户
         * @description 仅内建本地管理员可调用。
         */
        post: operations["disableAdminUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 编辑用户
         * @description 仅内建本地管理员可调用；该操作会修改全局用户身份。
         */
        patch: operations["updateAdminUser"];
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重置用户密码
         * @description 仅内建本地管理员可调用。
         */
        post: operations["resetAdminUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询设备列表 */
        get: operations["listAdminDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询设备详情 */
        get: operations["getAdminDevice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/devices/{device_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 禁用设备 */
        post: operations["disableAdminDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/devices/{device_id}/unbind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 解除设备绑定 */
        post: operations["unbindAdminDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/activation-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询激活码列表 */
        get: operations["listActivationCodes"];
        put?: never;
        /** 创建激活码 */
        post: operations["createActivationCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/activation-codes/{code_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 作废激活码 */
        post: operations["revokeActivationCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-pool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询模型池摘要 */
        get: operations["getModelPool"];
        put?: never;
        /** 新增模型账号 */
        post: operations["createModelPoolAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-pool/{account_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 禁用模型号池账号 */
        post: operations["disableModelPoolAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-pool/{account_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 测试 OpenAI-compatible 模型账号连通性
         * @description Go 使用服务端 Secret Store 中的账号密钥调用供应商测试接口；测试正文、API Key 和完整响应正文不返回客户端。
         *     服务端只返回测试状态、HTTP 状态、延迟、模型摘要和稳定错误码，并记录审计与健康状态。
         */
        post: operations["testModelPoolAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-pool/{account_id}/rotate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 轮换模型号池账号密钥
         * @description 新密钥先通过受限连通性测试，成功后写入 Secret Store；响应不会返回密钥原文。不同幂等键并发轮换时，后提交请求返回 MODEL_POOL_SECRET_ROTATION_CONFLICT，不能覆盖已提交密钥。
         */
        post: operations["rotateModelPoolAccountSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-pool/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 编辑模型号池账号非密钥配置 */
        patch: operations["updateModelPoolAccount"];
        trace?: never;
    };
    "/api/v1/admin/model-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询模型调用用量记录 */
        get: operations["listModelUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-leases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询模型租约
         * @description 返回脱敏的租约生命周期和归属摘要，不返回租约凭证、API Key 或模型正文。
         */
        get: operations["listModelLeases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-leases/{lease_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询单个模型租约详情
         * @description 返回脱敏的租约生命周期详情，不返回租约凭证、API Key 或模型正文。
         */
        get: operations["getModelLeaseAdminDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-leases/{lease_id}/reclaim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 管理员回收模型租约
         * @description 幂等释放指定租约；只改变租约生命周期，不返回凭证或模型正文。
         */
        post: operations["reclaimModelLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询审计日志 */
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活检查 */
        get: operations["livez"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 就绪检查 */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Id: string;
        /** Format: date-time */
        Timestamp: string;
        Sha256Hex: string;
        ErrorResponse: {
            /** @description 稳定错误码，供三端分支处理；审计持久化失败时返回 AUDIT_UNAVAILABLE（HTTP 503）并不会提交原业务响应 */
            code: string;
            /** @description 面向操作者的可读消息 */
            message: string;
            request_id: string;
            details?: components["schemas"]["ErrorDetail"][];
        };
        ErrorDetail: {
            field: string;
            reason: string;
        };
        /** @enum {string} */
        ActorRole: "admin" | "user";
        /** @enum {string} */
        ProductCode: "autolive" | "douyin_desktop";
        /** @enum {string} */
        UserStatus: "active" | "disabled";
        /** @enum {string} */
        DeviceStatus: "pending_activation" | "active" | "disabled" | "revoked";
        /** @enum {string} */
        ActivationCodeStatus: "active" | "used" | "expired" | "revoked";
        /** @enum {string} */
        ModelAccountStatus: "active" | "cooldown" | "exhausted" | "disabled";
        /** @enum {string} */
        ModelLeaseStatus: "active" | "released" | "expired";
        SessionTokens: {
            access_token: string;
            refresh_token: string;
            expires_at: components["schemas"]["Timestamp"];
        };
        UserSummary: {
            id: components["schemas"]["Id"];
            username: string;
            role: components["schemas"]["ActorRole"];
            status: components["schemas"]["UserStatus"];
            created_at: components["schemas"]["Timestamp"];
        };
        UserAuthorizationSummary: {
            user_id: components["schemas"]["Id"];
            device_count: number;
            active_device_count: number;
            active_lease_count: number;
            active_account_count: number;
            daily_used_tokens: number;
            /**
             * @description 客户端事后上报的软额度依据，不是供应商权威账单
             * @enum {string}
             */
            usage_source: "client_reported_soft";
            /** @description 当前版本不提供用户级供应商硬额度，固定为 false */
            hard_quota_configured: boolean;
            /** @description provider/model allowlist；空数组表示允许所有已登记模型 */
            allowed_models: string[];
            /** @description 服务端已接收用量门禁；0 表示未配置 */
            daily_token_limit: number;
            /**
             * @description 说明额度只基于服务端已接收记录，不代表供应商权威账单
             * @enum {string}
             */
            quota_enforcement: "server_recorded_usage_guard";
            as_of: components["schemas"]["Timestamp"];
        };
        DeviceSummary: {
            id: components["schemas"]["Id"];
            user_id: components["schemas"]["Id"];
            product: components["schemas"]["ProductCode"];
            device_name: string;
            platform: string;
            app_version: string;
            status: components["schemas"]["DeviceStatus"];
            /** @description 服务端依据最后心跳和固定阈值派生的在线状态 */
            online: boolean;
            disk_free_bytes?: number;
            memory_total_bytes?: number;
            memory_available_bytes?: number;
            cpu_logical_cores?: number;
            runtime_os_name?: string;
            runtime_os_version?: string;
            kernel_version?: string;
            current_media_name?: string;
            /** @enum {string} */
            playback_state?: "idle" | "playing" | "paused" | "error";
            last_seen_at: components["schemas"]["Timestamp"];
            /** @description 当前设备绑定的激活码到期时间；未绑定或历史数据缺失时省略 */
            activation_expires_at?: components["schemas"]["Timestamp"] | null;
        };
        LoginRequest: {
            username: string;
            password: string;
            product: components["schemas"]["ProductCode"];
        };
        LoginResponse: {
            request_id: string;
            tokens: components["schemas"]["SessionTokens"];
            user: components["schemas"]["UserSummary"];
        };
        RefreshTokenRequest: {
            refresh_token: string;
        };
        RefreshTokenResponse: {
            request_id: string;
            tokens: components["schemas"]["SessionTokens"];
        };
        /** @description 可选 refresh_token 仅为兼容客户端请求体；服务端只撤销当前 Bearer Token 对应会话，不会撤销其他会话。 */
        LogoutRequest: {
            refresh_token?: string;
        };
        LogoutResponse: {
            request_id: string;
            /** @constant */
            success: true;
        };
        ActivateDeviceRequest: {
            activation_code: string;
            device: components["schemas"]["DeviceRegistration"];
        };
        DeviceRegistration: {
            product: components["schemas"]["ProductCode"];
            device_id: components["schemas"]["Id"];
            device_name: string;
            platform: string;
            app_version: string;
            os_version?: string;
        };
        ActivateDeviceResponse: {
            request_id: string;
            device: components["schemas"]["DeviceSummary"];
        };
        HeartbeatRequest: {
            product: components["schemas"]["ProductCode"];
            device_id: components["schemas"]["Id"];
            sent_at: components["schemas"]["Timestamp"];
            status: {
                disk_free_bytes: number;
                memory_total_bytes?: number;
                memory_available_bytes?: number;
                cpu_logical_cores?: number;
                os_name?: string;
                os_version?: string;
                kernel_version?: string;
                current_media_name?: string;
                /** @enum {string} */
                playback_state?: "idle" | "playing" | "paused" | "error";
            };
        };
        HeartbeatResponse: {
            request_id: string;
            accepted_at: components["schemas"]["Timestamp"];
            device_status: components["schemas"]["DeviceStatus"];
        };
        ClientProfileResponse: {
            request_id: string;
            product: components["schemas"]["ProductCode"];
            user: components["schemas"]["UserSummary"];
            device: components["schemas"]["DeviceSummary"];
            permissions: string[];
        };
        CreateModelPoolAccountRequest: {
            provider: string;
            model: string;
            /**
             * Format: uri
             * @description OpenAI-compatible API 根地址，仅允许 http/https；不得包含密钥
             */
            base_url?: string;
            api_key: string;
            priority: number;
            daily_limit: number;
            concurrency_limit: number;
            /** @description 初始状态；默认 active，disabled 仍受活动租约规则约束 */
            status?: components["schemas"]["ModelAccountStatus"];
        };
        UpdateModelPoolAccountRequest: {
            /**
             * Format: uri
             * @description OpenAI-compatible API 根地址；不得包含密钥
             */
            base_url?: string;
            priority?: number;
            daily_limit?: number;
            concurrency_limit?: number;
            status?: components["schemas"]["ModelAccountStatus"];
        };
        TestModelPoolAccountRequest: {
            /** @default 15 */
            timeout_seconds: number;
        };
        RotateModelPoolAccountSecretRequest: {
            api_key: string;
            /** @default 15 */
            timeout_seconds: number;
        };
        ModelPoolConnectivityTestResponse: {
            request_id: string;
            account_id: components["schemas"]["Id"];
            /** @enum {string} */
            status: "succeeded" | "failed" | "timeout";
            tested_at: components["schemas"]["Timestamp"];
            latency_ms: number;
            http_status?: number;
            provider: string;
            model: string;
            response_summary?: string;
            /** @description 模型连通性失败原因；明文 HTTP 未显式允许时为 MODEL_POOL_CONNECTIVITY_INSECURE_HTTP */
            error_code?: string;
        };
        CreateModelLeaseRequest: {
            provider: string;
            model: string;
            /** @enum {string} */
            purpose: "realtime_script" | "chat" | "validation";
            /** @default 300 */
            max_duration_seconds: number;
        };
        RenewModelLeaseRequest: {
            /** @default 300 */
            extend_seconds: number;
        };
        ReleaseModelLeaseRequest: {
            reason?: string;
        };
        ModelLeaseResponse: {
            request_id: string;
            lease: components["schemas"]["ModelLease"];
        };
        ModelLease: {
            id: components["schemas"]["Id"];
            product: components["schemas"]["ProductCode"];
            provider: string;
            model: string;
            status: components["schemas"]["ModelLeaseStatus"];
            created_at?: components["schemas"]["Timestamp"];
            expires_at: components["schemas"]["Timestamp"];
            released_at?: components["schemas"]["Timestamp"];
            /** @enum {string} */
            proxy_mode: "direct_lease";
            concurrency_limit: number;
            /**
             * Format: uri
             * @description 当前租约允许访问的 OpenAI-compatible API 根地址；不得由客户端修改
             */
            readonly direct_base_url?: string;
        };
        ModelLeaseAdminSummary: {
            id: components["schemas"]["Id"];
            product: components["schemas"]["ProductCode"];
            account_id: components["schemas"]["Id"];
            user_id: components["schemas"]["Id"];
            device_id: components["schemas"]["Id"];
            purpose: string;
            provider: string;
            model: string;
            status: components["schemas"]["ModelLeaseStatus"];
            expires_at: components["schemas"]["Timestamp"];
            /** @enum {string} */
            proxy_mode: "direct_lease";
            concurrency_limit: number;
        };
        ModelLeaseListResponse: {
            request_id: string;
            items: components["schemas"]["ModelLeaseAdminSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        ModelLeaseAdminDetail: {
            id: components["schemas"]["Id"];
            product: components["schemas"]["ProductCode"];
            account_id: components["schemas"]["Id"];
            user_id: components["schemas"]["Id"];
            device_id: components["schemas"]["Id"];
            purpose: string;
            provider: string;
            model: string;
            status: components["schemas"]["ModelLeaseStatus"];
            created_at?: components["schemas"]["Timestamp"];
            expires_at: components["schemas"]["Timestamp"];
            released_at?: components["schemas"]["Timestamp"];
            /** @enum {string} */
            proxy_mode: "direct_lease";
            concurrency_limit: number;
        };
        ModelLeaseAdminDetailResponse: {
            request_id: string;
            lease: components["schemas"]["ModelLeaseAdminDetail"];
        };
        ReleaseModelLeaseResponse: {
            request_id: string;
            lease_id: components["schemas"]["Id"];
            released: boolean;
        };
        DirectLLMCallRecordRequest: {
            lease_id: components["schemas"]["Id"];
            client_call_id: components["schemas"]["Id"];
            provider: string;
            model: string;
            /** @enum {string} */
            status: "succeeded" | "failed" | "timeout" | "cancelled" | "unknown";
            /** @enum {string} */
            usage_source: "client_reported";
            input_tokens?: number;
            output_tokens?: number;
            total_tokens?: number;
            latency_ms?: number;
            error_code?: string;
            finish_reason?: string;
        };
        DirectLLMCallRecordResponse: {
            request_id: string;
            recorded: boolean;
        };
        Pagination: {
            page: number;
            page_size: number;
            total: number;
        };
        UserEnvelope: {
            request_id: string;
            user: components["schemas"]["UserSummary"];
        };
        UserAuthorizationSummaryResponse: {
            request_id: string;
            summary: components["schemas"]["UserAuthorizationSummary"];
        };
        UserAuthorizationPolicyResponse: {
            request_id: string;
            policy: components["schemas"]["UserAuthorizationPolicy"];
        };
        UserAuthorizationPolicy: {
            user_id: components["schemas"]["Id"];
            allowed_models: string[];
            daily_token_limit: number;
            updated_at: components["schemas"]["Timestamp"];
        };
        DeviceEnvelope: {
            request_id: string;
            device: components["schemas"]["DeviceSummary"];
        };
        UnbindDeviceResponse: {
            request_id: string;
            device_id: components["schemas"]["Id"];
            device_name: string;
            platform: string;
            status: components["schemas"]["DeviceStatus"];
            online: boolean;
            last_seen_at: components["schemas"]["Timestamp"];
        };
        UserListResponse: {
            request_id: string;
            items: components["schemas"]["UserSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        CreateUserRequest: {
            username: string;
            password: string;
            role: components["schemas"]["ActorRole"];
        };
        UpdateUserRequest: {
            username?: string;
            role?: components["schemas"]["ActorRole"];
            status?: components["schemas"]["UserStatus"];
        };
        UpdateUserAuthorizationRequest: {
            /** @description provider/model allowlist；空数组表示允许所有已登记模型 */
            allowed_models: string[];
            daily_token_limit: number;
        };
        ResetUserPasswordRequest: {
            password: string;
        };
        ChangeLocalAdminPasswordRequest: {
            password: string;
        };
        DeviceListResponse: {
            request_id: string;
            items: components["schemas"]["DeviceSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        CreateActivationCodeRequest: {
            expires_at: components["schemas"]["Timestamp"];
            /** @default 1 */
            max_devices: number;
        };
        ActivationCode: {
            id: components["schemas"]["Id"];
            product: components["schemas"]["ProductCode"];
            status: components["schemas"]["ActivationCodeStatus"];
            expires_at: components["schemas"]["Timestamp"];
            max_devices: number;
            /** @description 已成功绑定的设备数量，不超过 max_devices */
            bound_devices: number;
            /** @description 脱敏后的激活码前缀，不包含完整明文 */
            code_prefix?: string;
            /** @description 核销设备所属用户；仅核销后返回 */
            used_by_user_id?: components["schemas"]["Id"];
            /** @description 核销设备；仅核销后返回 */
            used_by_device_id?: components["schemas"]["Id"];
            /** @description 核销时间；仅核销后返回 */
            used_at?: components["schemas"]["Timestamp"];
            /** @description 仅创建响应中出现一次，列表与查询接口必须为 null */
            plain_code?: string | null;
        };
        ActivationCodeEnvelope: {
            request_id: string;
            activation_code: components["schemas"]["ActivationCode"];
        };
        ActivationCodeListResponse: {
            request_id: string;
            items: components["schemas"]["ActivationCode"][];
            pagination: components["schemas"]["Pagination"];
        };
        ModelPoolAccountEnvelope: {
            request_id: string;
            account: components["schemas"]["ModelPoolAccountSummary"];
        };
        ModelPoolAccountSummary: {
            id: components["schemas"]["Id"];
            product: components["schemas"]["ProductCode"];
            provider: string;
            model: string;
            /** Format: uri */
            base_url?: string;
            status: components["schemas"]["ModelAccountStatus"];
            priority: number;
            daily_limit: number;
            concurrency_limit: number;
            secret_configured: boolean;
            active_leases: number;
            daily_used_tokens: number;
            cooldown_until?: components["schemas"]["Timestamp"];
            /** @enum {string} */
            last_test_status?: "succeeded" | "failed" | "timeout";
            last_tested_at?: components["schemas"]["Timestamp"];
        };
        ModelPoolResponse: {
            request_id: string;
            accounts: components["schemas"]["ModelPoolAccountSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        ModelUsageRecord: {
            id: components["schemas"]["Id"];
            product: components["schemas"]["ProductCode"];
            lease_id: components["schemas"]["Id"];
            request_id: components["schemas"]["Id"];
            client_call_id: components["schemas"]["Id"];
            provider: string;
            model: string;
            input_tokens: number;
            output_tokens: number;
            total_tokens: number;
            latency_ms: number;
            /** @enum {string} */
            status: "succeeded" | "failed" | "timeout" | "cancelled" | "unknown";
            /** @enum {string} */
            usage_source: "client_reported";
            error_code?: string;
            created_at: components["schemas"]["Timestamp"];
        };
        ModelUsageListResponse: {
            request_id: string;
            items: components["schemas"]["ModelUsageRecord"][];
            pagination: components["schemas"]["Pagination"];
        };
        AuditLog: {
            id: components["schemas"]["Id"];
            product: components["schemas"]["ProductCode"];
            actor_user_id?: string | null;
            device_id?: string | null;
            action: string;
            target_type: string;
            target_id?: string | null;
            /** @enum {string} */
            outcome: "success" | "failure" | "unknown";
            status_code: number;
            error_code?: string | null;
            request_id?: string | null;
            created_at: components["schemas"]["Timestamp"];
        };
        AuditLogListResponse: {
            request_id: string;
            items: components["schemas"]["AuditLog"][];
            pagination: components["schemas"]["Pagination"];
        };
        HealthResponse: {
            request_id: string;
            /** @enum {string} */
            status: "ok" | "degraded";
            service: string;
            version: string;
            now: components["schemas"]["Timestamp"];
        };
    };
    responses: {
        /** @description 请求参数不合法 */
        BadRequest: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 未登录或会话失效 */
        Unauthorized: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 已登录但无权限或资源不可用 */
        Forbidden: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 状态冲突或重复请求语义不一致 */
        Conflict: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 达到限流或并发上限 */
        TooManyRequests: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                /** @description 建议客户端等待的秒数 */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 上游模型供应商返回失败或无效响应 */
        BadGateway: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 模型账号、直连租约、提交结果核对或供应商暂时不可用 */
        ServiceUnavailable: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 上游模型请求超时 */
        GatewayTimeout: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 当前路由不支持该请求方法 */
        MethodNotAllowed: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 请求在服务端完成前被取消 */
        RequestTimeout: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 未分类服务端异常 */
        InternalServerError: {
            headers: {
                "X-Request-Id": components["headers"]["X-Request-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 缺省 product 时仅允许取值 `legacy`，此时映射为 `autolive`；普通缺省登录请求返回 400，不从 User-Agent、版本、query 或其他 header 推断产品。 */
        LegacyClientCompatibilityHeader: "legacy";
        /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
        IdempotencyKeyHeader: string;
        LeaseId: components["schemas"]["Id"];
        Page: number;
        PageSize: number;
        /** @description 内建跨产品管理员省略时查询全部产品；其他管理员仅可查询认证会话所属产品。 */
        AdminProduct: components["schemas"]["ProductCode"];
    };
    requestBodies: never;
    headers: {
        /** @description 客户端提供合法值时服务端校验后透传；缺失或非法时由服务端生成请求追踪 ID */
        "X-Request-Id": string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authLogin: {
        parameters: {
            query?: never;
            header?: {
                /** @description 缺省 product 时仅允许取值 `legacy`，此时映射为 `autolive`；普通缺省登录请求返回 400，不从 User-Agent、版本、query 或其他 header 推断产品。 */
                "X-Client-Compatibility"?: components["parameters"]["LegacyClientCompatibilityHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    authRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description 刷新成功 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description 已退出 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
        };
    };
    clientActivate: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateDeviceRequest"];
            };
        };
        responses: {
            /** @description 激活成功 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivateDeviceResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    clientHeartbeat: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatRequest"];
            };
        };
        responses: {
            /** @description 心跳已接收 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    clientProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前身份摘要 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientProfileResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createModelLease: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateModelLeaseRequest"];
            };
        };
        responses: {
            /** @description 已返回可用租约 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelLeaseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    renewModelLease: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                lease_id: components["parameters"]["LeaseId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RenewModelLeaseRequest"];
            };
        };
        responses: {
            /** @description 续租成功或幂等返回当前租约 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelLeaseResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    releaseModelLease: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                lease_id: components["parameters"]["LeaseId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReleaseModelLeaseRequest"];
            };
        };
        responses: {
            /** @description 已释放或重复释放 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseModelLeaseResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    recordDirectLLMCall: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectLLMCallRecordRequest"];
            };
        };
        responses: {
            /** @description 调用摘要已记录；模型正文不经 Go 返回 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectLLMCallRecordResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["ServiceUnavailable"];
            504: components["responses"]["GatewayTimeout"];
        };
    };
    changeLocalAdminPassword: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeLocalAdminPasswordRequest"];
            };
        };
        responses: {
            /** @description 密码已修改并撤销管理员会话 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listAdminUsers: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                /** @description 内建跨产品管理员省略时查询全部产品；其他管理员仅可查询认证会话所属产品。 */
                product?: components["parameters"]["AdminProduct"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户分页列表 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createAdminUser: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listAdminUserDevices: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                /** @description 内建跨产品管理员省略时查询全部产品；其他管理员仅可查询认证会话所属产品。 */
                product?: components["parameters"]["AdminProduct"];
            };
            header?: never;
            path: {
                user_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户设备分页列表 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAdminUserAuthorizationSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户授权与软额度摘要 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAuthorizationSummaryResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateAdminUserAuthorization: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                user_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserAuthorizationRequest"];
            };
        };
        responses: {
            /** @description 用户授权策略已更新 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAuthorizationPolicyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    disableAdminUser: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                user_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户已禁用或已处于禁用状态 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    updateAdminUser: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                user_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description 用户已更新 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    resetAdminUserPassword: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                user_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetUserPasswordRequest"];
            };
        };
        responses: {
            /** @description 用户密码已重置，相关会话已撤销 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listAdminDevices: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                /** @description 内建跨产品管理员省略时查询全部产品；其他管理员仅可查询认证会话所属产品。 */
                product?: components["parameters"]["AdminProduct"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 设备分页列表 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAdminDevice: {
        parameters: {
            query?: {
                /** @description 内建跨产品管理员省略时查询全部产品；其他管理员仅可查询认证会话所属产品。 */
                product?: components["parameters"]["AdminProduct"];
            };
            header?: never;
            path: {
                device_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 设备详情 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
        };
    };
    disableAdminDevice: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                device_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 设备已禁用或已处于禁用状态 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    unbindAdminDevice: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                device_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 设备进入待激活状态；重新绑定需要新的激活码 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnbindDeviceResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listActivationCodes: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                /** @description 内建跨产品管理员省略时查询全部产品；其他管理员仅可查询认证会话所属产品。 */
                product?: components["parameters"]["AdminProduct"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 激活码分页列表 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivationCodeListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createActivationCode: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivationCodeRequest"];
            };
        };
        responses: {
            /** @description 创建成功；仅此响应可返回一次性明文激活码 */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivationCodeEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
        };
    };
    revokeActivationCode: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                code_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 激活码已作废；已核销或已过期激活码不能作废 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivationCodeEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getModelPool: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                /** @description 内建跨产品管理员省略时查询全部产品；其他管理员仅可查询认证会话所属产品。 */
                product?: components["parameters"]["AdminProduct"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 模型池摘要列表 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelPoolResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createModelPoolAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateModelPoolAccountRequest"];
            };
        };
        responses: {
            /** @description 创建成功，仅返回脱敏账号摘要 */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelPoolAccountEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    disableModelPoolAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 禁用成功；不会再分配新租约 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelPoolAccountEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    testModelPoolAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                account_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TestModelPoolAccountRequest"];
            };
        };
        responses: {
            /** @description 测试完成，结果已记录 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelPoolConnectivityTestResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    rotateModelPoolAccountSecret: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                account_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotateModelPoolAccountSecretRequest"];
            };
        };
        responses: {
            /** @description 新密钥已验证并切换 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelPoolAccountEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    updateModelPoolAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                account_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateModelPoolAccountRequest"];
            };
        };
        responses: {
            /** @description 编辑成功；API Key 不在此接口修改或返回 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelPoolAccountEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listModelUsage: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                /** @description 内建跨产品管理员省略时查询全部产品；其他管理员仅可查询认证会话所属产品。 */
                product?: components["parameters"]["AdminProduct"];
                provider?: string;
                model?: string;
                user_id?: components["schemas"]["Id"];
                device_id?: components["schemas"]["Id"];
                request_id?: components["schemas"]["Id"];
                /** @description 仅返回创建时间大于等于该 RFC3339 时间的记录。 */
                created_after?: components["schemas"]["Timestamp"];
                /** @description 仅返回创建时间小于等于该 RFC3339 时间的记录。 */
                created_before?: components["schemas"]["Timestamp"];
                sort?: "created_at_desc" | "created_at_asc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务端生成的模型用量记录 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelUsageListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listModelLeases: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                /** @description 内建跨产品管理员省略时查询全部产品；其他管理员仅可查询认证会话所属产品。 */
                product?: components["parameters"]["AdminProduct"];
                status?: "active" | "released" | "expired";
                provider?: string;
                model?: string;
                user_id?: components["schemas"]["Id"];
                device_id?: components["schemas"]["Id"];
                account_id?: components["schemas"]["Id"];
                sort?: "expires_at_desc" | "expires_at_asc" | "status" | "provider_model";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 模型租约分页列表 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelLeaseListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getModelLeaseAdminDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lease_id: components["parameters"]["LeaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 模型租约详情 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelLeaseAdminDetailResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
        };
    };
    reclaimModelLease: {
        parameters: {
            query?: never;
            header: {
                /** @description 写接口必填。相同认证主体、相同资源语义和相同幂等键的重复请求必须返回同一结果，不能重复产生副作用。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyHeader"];
            };
            path: {
                lease_id: components["parameters"]["LeaseId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReleaseModelLeaseRequest"];
            };
        };
        responses: {
            /** @description 租约已回收或已处于终态 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseModelLeaseResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                /** @description 内建跨产品管理员省略时查询全部产品；其他管理员仅可查询认证会话所属产品。 */
                product?: components["parameters"]["AdminProduct"];
                actor_user_id?: components["schemas"]["Id"];
                device_id?: components["schemas"]["Id"];
                action?: string;
                target_type?: string;
                outcome?: "success" | "failure" | "unknown";
                error_code?: string;
                request_id?: string;
                /** @description 包含该 RFC3339 时间点之后（含边界）的记录 */
                created_after?: components["schemas"]["Timestamp"];
                /** @description 包含该 RFC3339 时间点之前（含边界）的记录 */
                created_before?: components["schemas"]["Timestamp"];
                sort?: "created_at_desc" | "created_at_asc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 审计日志分页列表 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务健康状态 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
        };
    };
    livez: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 进程存活 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务已准备好接收流量 */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            408: components["responses"]["RequestTimeout"];
            500: components["responses"]["InternalServerError"];
            /** @description 依赖未就绪 */
            503: {
                headers: {
                    "X-Request-Id": components["headers"]["X-Request-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
